//$Id: InitializeCollectionEventListener.java,v 1.1 2008/01/14 09:32:44 b18146 Exp $
package org.hibernate.event;

import org.hibernate.HibernateException;

import java.io.Serializable;

/**
 * Defines the contract for handling of collection initialization events 
 * generated by a session.
 *
 * @author Gavin King
 */
public interface InitializeCollectionEventListener extends Serializable {

	public void onInitializeCollection(InitializeCollectionEvent event) throws HibernateException;

}
